# A reasonable number to start with
num_particles: 800
num_beams_per_particle: 100
 
# The field of view centered around theta=0
scan_field_of_view: 4.71 # radians
 
# Discretize the theta space for faster ray tracing
scan_theta_discretization: 500
 
map_topic: "/map"
scan_topic: "/scan"
odom_topic: "/odom"
 
do_viz: True
max_viz_particles: 60
squash_factor: 2.2
angle_step: 1.0
particle_filter_frame: "/base_link_pf"
 
deterministic: false
 
lidar_scale_to_map_scale: 1.0